version: "3.9"
services:
  gateway:
    build: ./api-gateway
    environment:
      - IS_DOCKER=true
    ports:
      - "80:5000"
  comment-service:
    build: ./comment-service
  customer-service:
    build: ./customer-service
  movie-service:
    build: ./movie-service
  notification-service:
    build: ./notification-service